# Default values for laa-amend-a-claim.
# These can be overwritten by values defined in environment specific values files.
replicaCount: 1

image:
  repository: laa-amend-a-claim
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  containerPort: 8000

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "modsec"
  cluster:
    name: green
    weight: '100'
  tls: {}

whitelist:
  enabled: true

resources: {}

autoscaling:
  enabled: false

volumes: []

volumeMounts: []
nodeSelector: {}

tolerations: []

affinity: {}

env:
  AZURE_CLIENT_ID:
    secret:
      name: laa-amend-a-claim-azure-client-id
      key: AZURE_CLIENT_ID
      optional: false
  AZURE_CLIENT_SECRET:
    secret:
      name: laa-amend-a-claim-azure-client-secret
      key: AZURE_CLIENT_SECRET
  AZURE_TENANT_ID:
    secret:
      name: laa-amend-a-claim-azure-tenant
      key: AZURE_TENANT_ID
  SENTRY_DSN:
    secret:
      name: laa-amend-a-claim-sentry-dsn
      key: SENTRY_DSN
  BASE_URL_HOMEPAGE:
    secret:
      name: laa-amend-a-claim-base-url
      key: BASE_URL_HOMEPAGE
  SENTRY_ENVIRONMENT:
    value: ${SENTRY_ENV}
  REDIS_URL:
    secret:
      name: elasticache-redis
      key: url
  ENTRA_ID_SKIP_AUTH:
    value: "False"
  CLAIMS_API:
    secret:
      name: laa-amend-a-claim-claims-api-url
      key: CLAIMS_API
  CLAIMS_TOKEN:
    secret:
      name: laa-amend-a-claim-claims-api-token
      key: CLAIMS_TOKEN
  ENTRA_ID_CLIENT_ID:
    secret:
      name: entra-id
      key: client_id
  ENTRA_ID_CLIENT_SECRET:
    secret:
      name: entra-id
      key: client_secret
  ENTRA_ID_CLIENT_SECRET_THUMBPRINT:
    secret:
      name: entra-id
      key: client_secret_thumbprint
  ENTRA_ID_AUTHORITY:
    secret:
      name: entra-id
      key: authority
  ENTRA_ID_REDIRECT_URI:
    secret:
      name: entra-id
      key: redirect_uri