services:
  wiremock:
    image: wiremock/wiremock:2.35.0
    container_name: wiremock
    ports:
      - "8081:8080" # Expose WireMock on port 8081
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
    command:
      - -local-response-templating
  redis:
    image: redis:8-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
  zap:
    image: zaproxy/zap-stable
    container_name: zap-proxy
    ports:
      - "8090:8090"
    extra_hosts:
      - "localhost:host-gateway"
    volumes:
      - ./zap-reports:/zap/wrk:rw
    command: >
      zap.sh -daemon -host 0.0.0.0
      -port 8090
      -config api.addrs.addr.name=.*
      -config api.addrs.addr.regex=true
      -config api.disablekey=true

volumes:
  redis_data:
