spring:
  application:
    name: LAA Amend a Claim Service
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: ${BASE_URL_HOMEPAGE}/login/oauth2/code/azure
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
          graph:
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: https://graph.microsoft.com/.default
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0
            token-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            jwk-set-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/discovery/v2.0/keys
          graph:
            token-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/token
  data:
    redis:
      url: ${REDIS_URL}
  session:
    timeout: 30m
sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENVIRONMENT}
claims-api:
  url: ${CLAIMS_API}
  access-token: ${CLAIMS_TOKEN}
microsoft-graph-api:
  url: https://graph.microsoft.com
search:
  sort-enabled: true
app:
  feedback-url: ${FEEDBACK_URL}
  laa-url: ${LAA_URL}

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.http.client: DEBUG
    org.springframework.web.client.support: TRACE
    org.apache.http.wire: DEBUG
    org.apache.http.headers: DEBUG
    org.springframework.session: INFO

management:
  server:
    port: 8182
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

---
spring:
  config:
    activate:
      on-profile: ephemeral
