{{- if .Values.dataClaimsApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "e2e-stack.claimsName" . }}
  labels:
    app: {{ include "e2e-stack.claimsName" . }}
spec:
  type: {{ .Values.dataClaimsApi.service.type }}
  selector:
    app: {{ include "e2e-stack.claimsName" . }}
  ports:
    - name: http
      port: {{ .Values.dataClaimsApi.service.port }}
      targetPort: http
    {{- if .Values.dataClaimsApi.service.metricsPort }}
    - name: metrics
      port: {{ .Values.dataClaimsApi.service.metricsPort }}
      targetPort: metrics
    {{- end }}
    {{- if .Values.dataClaimsApi.postgres.enabled }}
    - name: postgres
      port: 5435
      targetPort: postgres
    {{- end }}
{{- end }}
