apiVersion: v1
kind: Service
metadata:
  name: {{ include "laa-amend-a-claim.fullname" . }}
spec:
  selector: {{- include "laa-amend-a-claim.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: 8080
      targetPort: 8080