name: CI/CD Pipeline

on:
  - push

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.ref_name }}
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      branch: ${{ github.ref_name }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      CLAIMS_TOKEN: ${{ secrets.CLAIMS_TOKEN }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

  deploy-uat:
    name: Deploy to UAT
    if: github.ref_name == 'main'
    needs: [build, test]
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ github.ref_name }}
      environment: test
      SENTRY_ENV: test
      image_tag: ${{ needs.build.outputs.image_tag }}
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CERT: ${{ secrets.KUBE_CERT }}

  deploy-dev:
    name: Deploy to Dev
    if: github.ref_name != 'main'
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ github.ref_name }}
      environment: dev
      SENTRY_ENV: development
      image_tag: ${{ needs.build.outputs.image_tag }}
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CERT: ${{ secrets.KUBE_CERT }}