name: Feature Branch Pipeline

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read
  packages: write
  id-token: write
  security-events: write
  pull-requests: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.ref_name }}
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}

  deploy-ephemeral:
    name: Deploy Ephemeral Environment
    needs: build
    uses: ./.github/workflows/deploy-ephemeral.yml
    with:
      branch: ${{ github.ref_name }}
      image_tag: ${{ needs.build.outputs.image_tag }}
      aws_region: ${{ vars.ECR_REGION }}
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CERT: ${{ secrets.KUBE_CERT }}

  test:
    name: Test
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      branch: ${{ github.ref_name }}
      environment: dev
      amend_a_claim_image_tag: ${{ needs.build.outputs.image_tag }}
    secrets:
      P_USERNAME: ${{ secrets.P_USERNAME }}
      P_PASSWORD: ${{ secrets.P_PASSWORD }}
      P_MFA_SECRET: ${{ secrets.P_MFA_SECRET }}
      E2E_DB_PASSWORD: ${{ secrets.E2E_DB_PASSWORD }}
      E2E_DB_USER: ${{ secrets.E2E_DB_USER }}
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CERT: ${{ secrets.KUBE_CERT }}
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
      DATA_CLAIMS_API_IMAGE: ${{ secrets.DATA_CLAIMS_API_IMAGE }}

  security:
    name: Security
    needs: build
    uses: ./.github/workflows/security.yml
    with:
      branch: ${{ github.ref_name }}
      image_tag: ${{ needs.build.outputs.image_tag }}
      aws_region: ${{ vars.ECR_REGION }}
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}

  deploy-dev:
    name: Deploy to Dev
    needs: [ build, test ]
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ github.ref_name }}
      environment: dev
      SENTRY_ENV: development
      image_tag: ${{ needs.build.outputs.image_tag }}
      aws_region: ${{ vars.ECR_REGION }}
      values_file: values/dev.yaml
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CERT: ${{ secrets.KUBE_CERT }}
