name: Main Branch Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write
  security-events: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.ref_name }}
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}

  test:
    name: Test
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      branch: ${{ github.ref_name }}
      environment: dev
      amend_a_claim_image_tag: ${{ needs.build.outputs.image_tag }}
    secrets:
      P_USERNAME: ${{ secrets.P_USERNAME }}
      P_PASSWORD: ${{ secrets.P_PASSWORD }}
      P_MFA_SECRET: ${{ secrets.P_MFA_SECRET }}
      E2E_DB_PASSWORD: ${{ secrets.E2E_DB_PASSWORD }}
      E2E_DB_USER: ${{ secrets.E2E_DB_USER }}
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CERT: ${{ secrets.KUBE_CERT }}
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
      DATA_CLAIMS_API_IMAGE: ${{ secrets.DATA_CLAIMS_API_IMAGE }}

  security:
    name: Security
    needs: [build, test]
    uses: ./.github/workflows/security.yml
    with:
      branch: ${{ github.ref_name }}
      image_tag: ${{ needs.build.outputs.image_tag }}
      aws_region: ${{ vars.ECR_REGION }}
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}

  deploy-dev:
    name: Deploy to Dev
    needs: [build, test, security]
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ github.ref_name }}
      environment: dev
      SENTRY_ENV: development
      image_tag: ${{ needs.build.outputs.image_tag }}
      aws_region: ${{ vars.ECR_REGION }}
      values_file: values/dev.yaml
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CERT: ${{ secrets.KUBE_CERT }}
      BYPASS_PASSWORD: ${{ secrets.BYPASS_PASSWORD }}

  deploy-uat:
    name: Deploy to UAT
    needs: [build, test, security, deploy-dev]
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ github.ref_name }}
      environment: test
      SENTRY_ENV: test
      image_tag: ${{ needs.build.outputs.image_tag }}
      aws_region: ${{ vars.ECR_REGION }}
      values_file: values/uat.yaml
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CERT: ${{ secrets.KUBE_CERT }}
      BYPASS_PASSWORD: ${{ secrets.BYPASS_PASSWORD }}

  deploy-staging:
    name: Deploy to Staging
    needs: [ build, test, security, deploy-uat ]
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ github.ref_name }}
      environment: staging
      SENTRY_ENV: staging
      image_tag: ${{ needs.build.outputs.image_tag }}
      aws_region: ${{ vars.ECR_REGION }}
      values_file: values/staging.yaml
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CERT: ${{ secrets.KUBE_CERT }}
      BYPASS_PASSWORD: ${{ secrets.BYPASS_PASSWORD }}

  deploy-production:
    name: Deploy to Production
    needs: [ build, test, security, deploy-uat, deploy-staging ]
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ github.ref_name }}
      environment: production
      SENTRY_ENV: production
      image_tag: ${{ needs.build.outputs.image_tag }}
      aws_region: ${{ vars.ECR_REGION }}
      values_file: values/production.yaml
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CERT: ${{ secrets.KUBE_CERT }}
      BYPASS_PASSWORD: ${{ secrets.BYPASS_PASSWORD }}